
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action KonversiSuhuAction;

	private global::Gtk.Action KonverWaktuAction;

	private global::Gtk.Action CelsiusToFahrenheitAction;

	private global::Gtk.Action CelsiusToReamurAction;

	private global::Gtk.Action CeliusToKelvinAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.Label label4;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.KonversiSuhuAction = new global::Gtk.Action("KonversiSuhuAction", global::Mono.Unix.Catalog.GetString("Konversi Suhu"), null, null);
		this.KonversiSuhuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Konversi Suhu");
		w1.Add(this.KonversiSuhuAction, null);
		this.KonverWaktuAction = new global::Gtk.Action("KonverWaktuAction", global::Mono.Unix.Catalog.GetString("Konver Waktu"), null, null);
		this.KonverWaktuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Konver Waktu");
		w1.Add(this.KonverWaktuAction, null);
		this.CelsiusToFahrenheitAction = new global::Gtk.Action("CelsiusToFahrenheitAction", global::Mono.Unix.Catalog.GetString("Celsius To Fahrenheit"), null, null);
		this.CelsiusToFahrenheitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Celsius To Fahrenheit");
		w1.Add(this.CelsiusToFahrenheitAction, null);
		this.CelsiusToReamurAction = new global::Gtk.Action("CelsiusToReamurAction", global::Mono.Unix.Catalog.GetString("Celsius To Reamur"), null, null);
		this.CelsiusToReamurAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Celsius To Kelvin");
		w1.Add(this.CelsiusToReamurAction, null);
		this.CeliusToKelvinAction = new global::Gtk.Action("CeliusToKelvinAction", global::Mono.Unix.Catalog.GetString("Celius To Kelvin"), null, null);
		this.CeliusToKelvinAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Celius To Kelvin");
		w1.Add(this.CeliusToKelvinAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Konversi Simpel");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='KonversiSuhuAction' action='KonversiSuhuAction'><menuitem name='CelsiusToFahrenheitAction' action='CelsiusToFahrenheitAction'/><menuitem name='CelsiusToReamurAction' action='CelsiusToReamurAction'/><menuitem name='CeliusToKelvinAction' action='CeliusToKelvinAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.hbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.menubar1]));
		w2.Position = 0;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar2\'><menu name=\'KonverWaktuAction\' action=\'KonverWaktuAc" +
				"tion\'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.hbox1.Add(this.menubar2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.menubar2]));
		w3.Position = 1;
		w3.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Konversi Sederhana Suhu Dan Waktu");
		this.vbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
		w5.Position = 1;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 562;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KonverWaktuAction.Activated += new global::System.EventHandler(this.Onclick);
		this.CelsiusToFahrenheitAction.Activated += new global::System.EventHandler(this.Click);
		this.CelsiusToReamurAction.Activated += new global::System.EventHandler(this.onclick);
		this.CeliusToKelvinAction.Activated += new global::System.EventHandler(this.OnClick);
	}
}
