
// This file has been generated by the GUI designer. Do not modify.
namespace malas
{
	public partial class Window3
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Entry entry1;

		private global::Gtk.Label label8;

		private global::Gtk.Button button1;

		private global::Gtk.Label label4;

		private global::Gtk.Label label1;

		private global::Gtk.Label label5;

		private global::Gtk.Label label2;

		private global::Gtk.Label label6;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget malas.Window3
			this.Name = "malas.Window3";
			this.Title = global::Mono.Unix.Catalog.GetString("Konversi Waktu");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child malas.Window3.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed3.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry1]));
			w1.X = 177;
			w1.Y = 44;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Jumlah Detik");
			this.fixed3.Add(this.label8);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label8]));
			w2.X = 78;
			w2.Y = 47;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Konversi");
			this.fixed3.Add(this.button1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.button1]));
			w3.X = 142;
			w3.Y = 80;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.fixed3.Add(this.label4);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
			w4.X = 136;
			w4.Y = 130;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Jam");
			this.fixed3.Add(this.label1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label1]));
			w5.X = 192;
			w5.Y = 131;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.fixed3.Add(this.label5);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label5]));
			w6.X = 133;
			w6.Y = 169;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Menit");
			this.fixed3.Add(this.label2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
			w7.X = 191;
			w7.Y = 161;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.fixed3.Add(this.label6);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label6]));
			w8.X = 130;
			w8.Y = 200;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Detik");
			this.fixed3.Add(this.label3);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
			w9.X = 191;
			w9.Y = 197;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.Onclik);
		}
	}
}
