
// This file has been generated by the GUI designer. Do not modify.
namespace malas
{
	public partial class Window2
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Entry entry2;

		private global::Gtk.Label label5;

		private global::Gtk.Button button2;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget malas.Window2
			this.Name = "malas.Window2";
			this.Title = global::Mono.Unix.Catalog.GetString("Celsius To Kelvin");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child malas.Window2.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed2.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry2]));
			w1.X = 169;
			w1.Y = 90;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Celsius");
			this.fixed2.Add(this.label5);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label5]));
			w2.X = 93;
			w2.Y = 96;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("Konversi");
			this.fixed2.Add(this.button2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button2]));
			w3.X = 152;
			w3.Y = 141;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Kelvin");
			this.fixed2.Add(this.label6);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label6]));
			w4.X = 87;
			w4.Y = 188;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("0");
			this.fixed2.Add(this.label7);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label7]));
			w5.X = 176;
			w5.Y = 185;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button2.Clicked += new global::System.EventHandler(this.OnClick);
		}
	}
}
